apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: weather-web
  description: Get the best weather here!
spec:
  type: website
  lifecycle: production
  owner: maaroen
  system: backstage-weather-demo
#  dependsOn:
#    - resource:default/artists-db
  consumesApis:
    - weather-api
